name: 'steam-workshop-upload'
description: 'Upload your mod to the Steam Workshop with the power of GitHub Actions — now with Steam Guard 2FA support'

branding:
  icon: upload-cloud
  color: purple

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  appid:
    description: 'Steam App ID'
    required: true
  itemid:
    description: 'Workshop Item ID'
    required: true
  path:
    description: 'Path of folder to upload'
    required: true
  changenote:
    description: 'Changenote of this update'
    required: false
    default: ${{ github.event.head_commit.message }}
  visibility:
    required: false
    default: '0'
  title:
    required: false
    default: ${{ github.event.repository.name }
  description:
    required: false
    default: ${{ github.event.head_commit.message }}
  previewfile:
    required: false
    default: 'thumbnail.png'